{% set name = "PyYAML-ft" %}
{% set version = "8.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyyaml_ft-{{ version }}.tar.gz
  sha256: 0c947dce03954c7b5d38869ed4878b2e6ff1d44b08a0d84dc83fdad205ae39ab
  patches:
    - patches/0001-Ensure-we-do-not-end-up-wih-CRLF-line-endings-on-tes.patch

build:
  number: 0
  skip: true  # [py<313]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython >=3.1
    - pip
    - yaml
  run:
    - python
    - yaml

test:
  source_files:
    - tests
  imports:
    - yaml_ft
    - yaml_ft._yaml
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/Quansight-Labs/pyyaml-ft
  summary: YAML parser and emitter for Python with support for free-threading
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    A full-featured YAML processing framework for Python with support for free-threading
  dev_url: https://github.com/Quansight-Labs/pyyaml-ft
  doc_url: https://github.com/Quansight-Labs/pyyaml-ft/blob/main/README.md

extra:
  recipe-maintainers:
    - zklaus
    - lysnikolaou
    - rgommers
    - ngoldbaum
